-- GENERIERT von scripts/gen-pflege-import.mjs — nicht von Hand editieren.
-- Import der Excel-Pflegepläne 2026 (BEW/JOPE/ALLCURA) in die Pflegeplanung.
-- Idempotent: ersetzt vorhandene Pläne für 2026.

delete from pflege_plaene where jahr = 2026;

-- ── BL · BL (Blankenburg) · 93 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('blankenburg', '', 2026, 'aktiv', '')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[{"von_monat":4,"bis_monat":11,"turnus":"monatlich","stunden_pro_gang":3}]'::jsonb, '{"14":3,"19":3,"23":3,"28":3,"32":3,"36":3,"41":3,"45":3}'::jsonb, 24, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[{"von_monat":5,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":1},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"19":1,"23":1,"28":1,"32":1,"36":1,"41":1,"45":2}'::jsonb, 8, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"14":2}'::jsonb, 2, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'pflanzen', '[{"von_monat":4,"bis_monat":5,"turnus":"monatlich","stunden_pro_gang":1},{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"14":1,"19":1,"28":1,"36":1,"45":2}'::jsonb, 6, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[{"von_monat":4,"bis_monat":5,"turnus":"monatlich","stunden_pro_gang":1},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"14":1,"19":1,"45":2}'::jsonb, 4, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen.', 'bewaesserung', '[{"von_monat":3,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":4},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"12":4,"14":4,"19":4,"23":4,"28":4,"32":4,"36":4,"41":4,"45":2}'::jsonb, 34, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"45":2}'::jsonb, 2, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"14":2}'::jsonb, 2, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC). Entweder durch…', 'Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kraftwerksleiter oder Pflegekräfte', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":5,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":1}]'::jsonb, '{"14":2,"19":1,"23":1,"28":1,"32":1,"36":1,"41":1}'::jsonb, 8, 8),
    ('kletterhilfen', 'Anbringen Kletterhilfen. Nur nach Absprache.', 'Anbringen Kletterhilfen. Nur nach Absprache.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren auf Funktion, Zustand und Ko…', 'Überprüfung von Bioreaktoren auf Funktion, Zustand und Kompostreifung', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 12),
    ('bienenweide', 'Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfer…', 'Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfernung und Nachsaat Bienenweide.', 'spezial', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"45":2}'::jsonb, 2, 13),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 14),
    ('ibc_reinigung', 'Reinigung IBC/Algenentfernung', 'Reinigung IBC/Algenentfernung', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"45":1}'::jsonb, 1, 15)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (12, 'Frühjahrspflege BL (KW 12)', '[{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":4}]'::jsonb, 4),
  (14, 'Frühjahrspflege BL (KW 14)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":4},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":2},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":2}]'::jsonb, 15),
  (19, 'Sommerpflege BL (KW 19)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":4},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 11),
  (23, 'Sommerpflege BL (KW 23)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":4},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 9),
  (28, 'Sommerpflege BL (KW 28)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":4},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 10),
  (32, 'Sommerpflege BL (KW 32)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":4},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 9),
  (36, 'Sommerpflege BL (KW 36)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":4},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 10),
  (41, 'Herbstpflege BL (KW 41)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":4},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 9),
  (45, 'Herbstpflege BL (KW 45)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":2},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2},{"titel":"Abbau von Schläuchen und wasserführenden Teilen und Erinneru","stunden":2},{"titel":"Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfernun","stunden":2},{"titel":"Reinigung IBC/Algenentfernung","stunden":1}]'::jsonb, 16)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── MV · MV (Tiny Forest) · 90.25 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('mv-bew', '', 2026, 'aktiv', '')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[{"von_monat":4,"bis_monat":11,"turnus":"monatlich","stunden_pro_gang":2}]'::jsonb, '{"14":2,"19":2,"23":2,"28":2,"32":2,"36":2,"41":2,"45":2}'::jsonb, 16, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[{"von_monat":4,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":1},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"14":1,"19":1,"23":1,"28":1,"32":1,"36":1,"41":1,"45":2}'::jsonb, 9, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"14":2}'::jsonb, 2, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'pflanzen', '[{"von_monat":4,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":1},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"14":1,"19":1,"23":1,"28":1,"32":1,"36":1,"41":1,"45":2}'::jsonb, 9, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[{"von_monat":4,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":4},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"14":4,"19":4,"23":4,"28":4,"32":4,"36":4,"41":4,"45":2}'::jsonb, 30, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":4},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"14":4,"45":2}'::jsonb, 6, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"45":2}'::jsonb, 2, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":5,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":0.5}]'::jsonb, '{"14":2,"19":0.5,"23":0.5,"28":0.5,"32":0.5,"36":0.5,"41":0.5}'::jsonb, 5, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC). Entweder durch…', 'Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kraftwerksleiter oder Pflegekräfte', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":5,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":1}]'::jsonb, '{"14":2,"19":1,"23":1,"28":1,"32":1,"36":1,"41":1}'::jsonb, 8, 8),
    ('kletterhilfen', 'Anbringen Kletterhilfen. Nur nach Absprache.', 'Anbringen Kletterhilfen. Nur nach Absprache.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren auf Funktion, Zustand und Ko…', 'Überprüfung von Bioreaktoren auf Funktion, Zustand und Kompostreifung', 'spezial', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":0.25}]'::jsonb, '{"14":0.25}'::jsonb, 0.25, 12),
    ('bienenweide', 'Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfer…', 'Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfernung und Nachsaat Bienenweide.', 'spezial', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"45":2}'::jsonb, 2, 13),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 14),
    ('ibc_reinigung', 'Reinigung IBC/Algenentfernung', 'Reinigung IBC/Algenentfernung', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"45":1}'::jsonb, 1, 15)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (14, 'Frühjahrspflege MV (KW 14)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":4},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":2},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":2},{"titel":"Überprüfung von Bioreaktoren auf Funktion, Zustand und Kompo","stunden":0.25}]'::jsonb, 18.25),
  (19, 'Sommerpflege MV (KW 19)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":0.5},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 9.5),
  (23, 'Sommerpflege MV (KW 23)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":0.5},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 9.5),
  (28, 'Sommerpflege MV (KW 28)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":0.5},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 9.5),
  (32, 'Sommerpflege MV (KW 32)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":0.5},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 9.5),
  (36, 'Sommerpflege MV (KW 36)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":0.5},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 9.5),
  (41, 'Herbstpflege MV (KW 41)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":0.5},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":1}]'::jsonb, 9.5),
  (45, 'Herbstpflege MV (KW 45)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":2},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2},{"titel":"Abbau von Schläuchen und wasserführenden Teilen und Erinneru","stunden":2},{"titel":"Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfernun","stunden":2},{"titel":"Reinigung IBC/Algenentfernung","stunden":1}]'::jsonb, 15)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── SH · SH (Scharnhorststraße) · 7 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('sh', '', 2026, 'aktiv', '')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"45":2}'::jsonb, 2, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"15":1}'::jsonb, 1, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC). Entweder durch…', 'Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kraftwerksleiter oder Pflegekräfte', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":3}]'::jsonb, '{"15":3}'::jsonb, 3, 8),
    ('kletterhilfen', 'Anbringen Kletterhilfen. Nur nach Absprache.', 'Anbringen Kletterhilfen. Nur nach Absprache.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren auf Funktion, Zustand und Ko…', 'Überprüfung von Bioreaktoren auf Funktion, Zustand und Kompostreifung', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 12),
    ('bienenweide', 'Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfer…', 'Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfernung und Nachsaat Bienenweide.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 13),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 14),
    ('ibc_reinigung', 'Reinigung IBC/Algenentfernung', 'Reinigung IBC/Algenentfernung', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"15":1}'::jsonb, 1, 15),
    ('', 'Kontrolle Lehmquelle, reinigung. Kontrolle Vogelkästen =…', 'Kontrolle Lehmquelle, reinigung. Kontrolle Vogelkästen = Reinigung.', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":8,"bis_monat":8,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":3}]'::jsonb, '{"15":2,"32":2,"46":3}'::jsonb, 7, 16)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (15, 'Frühjahrspflege SH (KW 15)', '[{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":1},{"titel":"Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kr","stunden":3},{"titel":"Reinigung IBC/Algenentfernung","stunden":1},{"titel":"Kontrolle Lehmquelle, reinigung. Kontrolle Vogelkästen = Rei","stunden":2}]'::jsonb, 7),
  (32, 'Sommerpflege SH (KW 32)', '[{"titel":"Kontrolle Lehmquelle, reinigung. Kontrolle Vogelkästen = Rei","stunden":2}]'::jsonb, 2),
  (45, 'Herbstpflege SH (KW 45)', '[{"titel":"Abbau von Schläuchen und wasserführenden Teilen und Erinneru","stunden":2}]'::jsonb, 2),
  (46, 'Herbstpflege SH (KW 46)', '[{"titel":"Kontrolle Lehmquelle, reinigung. Kontrolle Vogelkästen = Rei","stunden":3}]'::jsonb, 3)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── AG · AG · 8 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('ag', '', 2026, 'aktiv', '')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":8}]'::jsonb, '{"47":8}'::jsonb, 8, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC). Entweder durch…', 'Auffüllen von Bewässerungseinheiten (IBC). Entweder durch Kraftwerksleiter oder Pflegekräfte', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 8),
    ('kletterhilfen', 'Anbringen Kletterhilfen. Nur nach Absprache.', 'Anbringen Kletterhilfen. Nur nach Absprache.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren auf Funktion, Zustand und Ko…', 'Überprüfung von Bioreaktoren auf Funktion, Zustand und Kompostreifung', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 12),
    ('bienenweide', 'Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfer…', 'Abdecken Bienenweide mit Folie für 12 Monate. Dann Entfernung und Nachsaat Bienenweide.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 13),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 14),
    ('ibc_reinigung', 'Reinigung IBC/Algenentfernung', 'Reinigung IBC/Algenentfernung', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 15),
    ('', 'Kontrolle Lehmquelle, reinigung. Kontrolle Vogelkästen =…', 'Kontrolle Lehmquelle, reinigung. Kontrolle Vogelkästen = Reinigung.', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 16)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (47, 'Herbstpflege AG (KW 47)', '[{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":8}]'::jsonb, 8)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── H14 · H14 (Hermannstraße 14) · 49 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('h14', '', 2026, 'aktiv', 'Hier ist wichtig die Bewässerung anzustellen.')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[{"von_monat":4,"bis_monat":5,"turnus":"monatlich","stunden_pro_gang":2},{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":9,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"15":2,"22":2,"29":2,"36":2,"42":2,"48":1}'::jsonb, 11, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[{"von_monat":4,"bis_monat":5,"turnus":"monatlich","stunden_pro_gang":1},{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":9,"bis_monat":11,"turnus":"monatlich","stunden_pro_gang":1}]'::jsonb, '{"15":1,"22":1,"29":1,"36":1,"42":1,"48":1}'::jsonb, 6, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"15":1}'::jsonb, 1, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'pflanzen', '[{"von_monat":3,"bis_monat":3,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":5,"bis_monat":5,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":9,"bis_monat":11,"turnus":"monatlich","stunden_pro_gang":1}]'::jsonb, '{"12":1,"15":1,"18":1,"22":1,"29":1,"36":1,"42":1,"48":1}'::jsonb, 8, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":5,"bis_monat":5,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":10,"bis_monat":10,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":1,"22":2,"29":1,"36":2,"42":1,"48":2}'::jsonb, 9, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen. Kontrolle von Bewässerungssystemen.', 'bewaesserung', '[{"von_monat":4,"bis_monat":5,"turnus":"monatlich","stunden_pro_gang":1},{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":9,"bis_monat":11,"turnus":"monatlich","stunden_pro_gang":1}]'::jsonb, '{"15":1,"22":1,"29":1,"36":1,"42":1,"48":1}'::jsonb, 6, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"48":2}'::jsonb, 2, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"15":1}'::jsonb, 1, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC).', 'Auffüllen von Bewässerungseinheiten (IBC).', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 8),
    ('dachgarten', 'Dachgarten: Pflege des Dachgartens mit Rückschnitt von Ge…', 'Dachgarten: Pflege des Dachgartens mit Rückschnitt von Gehölzen, Mulchen, Pflanzenschutz, Düngen, Bodenverbesserung, Entfernung von Beikräutern, Kontrolle und Wartung der Bewässerungsanlage inkl. Frostsicherung und Inbetriebnahme, Nachpflanzungen sowie laufende Pflege von Stauden, Gräsern und Dachabläufen. Kommunikation mit Stakeholdern.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'spezial', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2,"48":2}'::jsonb, 4, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zust…', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand und Kompostreifung', 'spezial', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"48":1}'::jsonb, 1, 12),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 13)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (12, 'Frühjahrspflege H14 (KW 12)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1}]'::jsonb, 1),
  (15, 'Frühjahrspflege H14 (KW 15)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":1},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":1},{"titel":"Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterb","stunden":2}]'::jsonb, 10),
  (18, 'Frühjahrspflege H14 (KW 18)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1}]'::jsonb, 1),
  (22, 'Sommerpflege H14 (KW 22)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":1}]'::jsonb, 7),
  (29, 'Sommerpflege H14 (KW 29)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":1}]'::jsonb, 6),
  (36, 'Sommerpflege H14 (KW 36)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":1}]'::jsonb, 7),
  (42, 'Herbstpflege H14 (KW 42)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":1},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":1}]'::jsonb, 6),
  (48, 'Herbstpflege H14 (KW 48)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":1},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":1},{"titel":"Abbau von Schläuchen und wasserführenden Teilen und Erinneru","stunden":2},{"titel":"Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterb","stunden":2},{"titel":"Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand","stunden":1}]'::jsonb, 11)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── S3 · S3 Sickingstraße · 111.2 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('s3', '', 2026, 'aktiv', 'Zielbild Definition & Objektbeschreibung Die Sickingenstraße 3 ist vielfältig. Die Innenhöfe sind mit Baum/Gehölzen bepflanzt die im Herbst einen starken Rückschnitt brauchen um nicht zuviel Licht aus dem Innenhof zu nehmen. Es muss regelmäßig Beikräuter entfernt werden und vorhandene Stauden haben sich bereits so etabliert, dass man sie Umsetzen und in anderen Teilen des Projektes weitervermehren kann - es muss also nichts zugekauft werden bei Trittschäden oder Hundezerstörungen. Mit dem automatischen Bewässerungssystem ist der Müllplatz und der Dachgarten versorgt. Dort muss bei jedem Pflegegang geprüft werden ob der Wasseranschluss eingeschaltet und alle Komponenten funktionsfähig sind. Das Bewässerungssystem ist vorhanden mit allen Bauteilen aber die fliegen grad irgendwo herum und ich weiss nicht wo. Es müssen aber alle Teile angeschlossen werden und in Betrieb gesetzt werden.')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":8},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":4},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":4},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":8}]'::jsonb, '{"15":8,"23":4,"31":4,"38":4,"46":8}'::jsonb, 28, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":8},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":8}]'::jsonb, '{"15":8,"46":8}'::jsonb, 16, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2}'::jsonb, 2, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen) &…', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & Alle Dachflächen Beikräuter entfernen', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":6},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":6},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":6},{"von_monat":10,"bis_monat":10,"turnus":"einmalig","stunden_pro_gang":4},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":6},{"von_monat":12,"bis_monat":12,"turnus":"einmalig","stunden_pro_gang":4}]'::jsonb, '{"15":6,"23":6,"31":6,"38":6,"43":4,"46":6,"49":4}'::jsonb, 38, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":3},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":3},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":3},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":3}]'::jsonb, '{"15":3,"23":3,"31":3,"38":3,"46":3}'::jsonb, 15, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen. Kontrolle von Bewässerungssystemen.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":0.5},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":0.5},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2,"23":0.5,"31":0.5,"38":0.5,"46":2}'::jsonb, 5.5, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"46":2}'::jsonb, 2, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2}'::jsonb, 2, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC).', 'Auffüllen von Bewässerungseinheiten (IBC).', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 8),
    ('kletterhilfen', 'Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen', 'Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen', 'spezial', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"15":1,"46":1}'::jsonb, 2, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zust…', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand und Kompostreifung', 'spezial', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":0.35},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":0.35}]'::jsonb, '{"15":0.35,"46":0.35}'::jsonb, 0.7, 12),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 13)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (15, 'Frühjahrspflege S3 (KW 15)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":8},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":8},{"titel":"Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":6},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":2},{"titel":"Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen","stunden":1},{"titel":"Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand","stunden":0.35}]'::jsonb, 32.35),
  (23, 'Sommerpflege S3 (KW 23)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":4},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":6},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":0.5}]'::jsonb, 13.5),
  (31, 'Sommerpflege S3 (KW 31)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":4},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":6},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":0.5}]'::jsonb, 13.5),
  (38, 'Sommerpflege S3 (KW 38)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":4},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":6},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":0.5}]'::jsonb, 13.5),
  (43, 'Herbstpflege S3 (KW 43)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":4}]'::jsonb, 4),
  (46, 'Herbstpflege S3 (KW 46)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":8},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":8},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":6},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2},{"titel":"Abbau von Schläuchen und wasserführenden Teilen und Erinneru","stunden":2},{"titel":"Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen","stunden":1},{"titel":"Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand","stunden":0.35}]'::jsonb, 30.35),
  (49, 'Herbstpflege S3 (KW 49)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":4}]'::jsonb, 4)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── R95 · R95 · 111.2 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('r95', '', 2026, 'aktiv', '')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden), Beikräutern + H…', 'Entfernung alter Pflanzenteile (Stauden), Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":6},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":4},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":4},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":12}]'::jsonb, '{"15":6,"23":4,"31":4,"38":4,"46":12}'::jsonb, 30, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":4},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":6}]'::jsonb, '{"15":4,"46":6}'::jsonb, 10, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2}'::jsonb, 2, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":8},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":6},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":6},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":8}]'::jsonb, '{"15":8,"23":6,"31":6,"38":6,"46":8}'::jsonb, 34, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":3},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":3},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":3},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":3}]'::jsonb, '{"15":3,"23":3,"31":3,"38":3,"46":3}'::jsonb, 15, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen. Kontrolle von Bewässerungssystemen.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":0.5},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":0.5},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2,"23":0.5,"31":0.5,"38":0.5,"46":2}'::jsonb, 5.5, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"46":2}'::jsonb, 2, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2}'::jsonb, 2, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC).', 'Auffüllen von Bewässerungseinheiten (IBC).', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 8),
    ('dachgarten', 'Kontrolle Dachgarten Fahrradschuppen', 'Kontrolle Dachgarten Fahrradschuppen', 'spezial', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2,"31":2,"46":2}'::jsonb, 6, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'spezial', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":4}]'::jsonb, '{"46":4}'::jsonb, 4, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zust…', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand und Kompostreifung', 'spezial', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":0.35},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":0.35}]'::jsonb, '{"15":0.35,"46":0.35}'::jsonb, 0.7, 12),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 13)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (15, 'Frühjahrspflege R95 (KW 15)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden), Beikräutern + Hoch","stunden":6},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":4},{"titel":"Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":8},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":2},{"titel":"Kontrolle Dachgarten Fahrradschuppen","stunden":2},{"titel":"Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand","stunden":0.35}]'::jsonb, 29.35),
  (23, 'Sommerpflege R95 (KW 23)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden), Beikräutern + Hoch","stunden":4},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":6},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":0.5}]'::jsonb, 13.5),
  (31, 'Sommerpflege R95 (KW 31)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden), Beikräutern + Hoch","stunden":4},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":6},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":0.5},{"titel":"Kontrolle Dachgarten Fahrradschuppen","stunden":2}]'::jsonb, 15.5),
  (38, 'Sommerpflege R95 (KW 38)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden), Beikräutern + Hoch","stunden":4},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":6},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":0.5}]'::jsonb, 13.5),
  (46, 'Herbstpflege R95 (KW 46)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden), Beikräutern + Hoch","stunden":12},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":6},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":8},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2},{"titel":"Abbau von Schläuchen und wasserführenden Teilen und Erinneru","stunden":2},{"titel":"Kontrolle Dachgarten Fahrradschuppen","stunden":2},{"titel":"Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterb","stunden":4},{"titel":"Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand","stunden":0.35}]'::jsonb, 39.35)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── P15 · P15 (Putlitzstraße 15) · 50.5 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('p15', '', 2026, 'aktiv', 'Hier muss darauf geachtet werden, dass es einen Dachgarten gibt, bzw eine Solaranlage für die wir mitverantwortlich sind. Und die Begrünung der Garagen/Stellplatzüberdachungen.')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":3},{"von_monat":6,"bis_monat":6,"turnus":"einmalig","stunden_pro_gang":3},{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":3}]'::jsonb, '{"15":3,"23":3,"31":2,"38":2,"46":3}'::jsonb, 13, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":3},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":3}]'::jsonb, '{"15":3,"46":3}'::jsonb, 6, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.) +…', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.) + Kontrolle der Fermenter', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2}'::jsonb, 2, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":2},{"von_monat":9,"bis_monat":12,"turnus":"monatlich","stunden_pro_gang":2}]'::jsonb, '{"15":2,"23":2,"31":2,"38":2,"43":2,"46":2,"49":2}'::jsonb, 14, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen. Kontrolle von Bewässerungssystemen.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":0.5},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":0.5},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"15":1,"23":0.5,"31":0.5,"38":0.5,"46":1}'::jsonb, 3.5, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"46":2}'::jsonb, 2, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2}'::jsonb, 2, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC).', 'Auffüllen von Bewässerungseinheiten (IBC).', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 8),
    ('kletterhilfen', 'Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen', 'Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen', 'spezial', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":1}]'::jsonb, '{"15":1,"46":1}'::jsonb, 2, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('dachgarten', 'Dachgarten: Pflege des Dachgartens mit Rückschnitt. Solar…', 'Dachgarten: Pflege des Dachgartens mit Rückschnitt. Solaranlage muss freigehalten werden. Reporting bei Auffälligkeiten. Keine Wässerung oder Düngung.', 'spezial', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2,"31":2,"46":2}'::jsonb, 6, 12),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 13)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (15, 'Frühjahrspflege P15 (KW 15)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":3},{"titel":"Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.) + Kon","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":1},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":2},{"titel":"Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen","stunden":1},{"titel":"Dachgarten: Pflege des Dachgartens mit Rückschnitt. Solaranl","stunden":2}]'::jsonb, 16),
  (23, 'Sommerpflege P15 (KW 23)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":0.5}]'::jsonb, 5.5),
  (31, 'Sommerpflege P15 (KW 31)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":0.5},{"titel":"Dachgarten: Pflege des Dachgartens mit Rückschnitt. Solaranl","stunden":2}]'::jsonb, 6.5),
  (38, 'Sommerpflege P15 (KW 38)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":0.5}]'::jsonb, 4.5),
  (43, 'Herbstpflege P15 (KW 43)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":2}]'::jsonb, 2),
  (46, 'Herbstpflege P15 (KW 46)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":3},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":3},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":2},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":1},{"titel":"Abbau von Schläuchen und wasserführenden Teilen und Erinneru","stunden":2},{"titel":"Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen","stunden":1},{"titel":"Dachgarten: Pflege des Dachgartens mit Rückschnitt. Solaranl","stunden":2}]'::jsonb, 14),
  (49, 'Herbstpflege P15 (KW 49)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":2}]'::jsonb, 2)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── X13 · X13 (Kreuzbergstraße 13) · 56.2 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('e52ve8z3', '', 2026, 'aktiv', 'Hier in der Kreuzbergstraße ist das Berlin Büro von JOPE, also dem Auftraggeber. Hier ist es wichtig, dass es immer gepflegt aussieht und wir einen sehr guten Eindruck hinterlassen. JOhannes hat letztes Jahr den Wunsch geäußert an diesem Standort mehr Blühstauden zu pflanzen. Die muss ich noch bestellen (Ist noch nciht passiert). Wichtig ist auch hier immer die Wärmepumpen freizuschneiden damit dort nicht reinkommt und den Rasen gepflegt aussehen zu lassen. Den Rasen könnte man vlt. mal düngen und regelmäßig bei Trockenheit gießen. Eine zusätzliche Maßnahme wäre noch die Rundholzbeetbegrenzung hier mal zu installieren. Aber dafür muss erstmal passende Material irgendwo anfallen.')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":2},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2,"23":2,"31":2,"38":2,"46":2}'::jsonb, 10, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2,"46":2}'::jsonb, 4, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2}'::jsonb, 2, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen) &…', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & Alle Dachflächen Beikräuter entfernen', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":2},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2,"23":2,"31":2,"38":2,"46":2}'::jsonb, 10, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":3},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":3},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":3},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":3}]'::jsonb, '{"15":3,"23":3,"31":3,"38":3,"46":3}'::jsonb, 15, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen. Kontrolle von Bewässerungssystemen.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":6,"bis_monat":7,"turnus":"monatlich","stunden_pro_gang":2},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2,"23":2,"31":2,"38":2,"46":2}'::jsonb, 10, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":0.5}]'::jsonb, '{"46":0.5}'::jsonb, 0.5, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"15":2}'::jsonb, 2, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC).', 'Auffüllen von Bewässerungseinheiten (IBC).', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 8),
    ('kletterhilfen', 'Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen', 'Anbringen Kletterhilfen bzw Hochbinden von Kletterpflanzen', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'spezial', '[{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"46":2}'::jsonb, 2, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zust…', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand und Kompostreifung', 'spezial', '[{"von_monat":4,"bis_monat":4,"turnus":"einmalig","stunden_pro_gang":0.35},{"von_monat":11,"bis_monat":11,"turnus":"einmalig","stunden_pro_gang":0.35}]'::jsonb, '{"15":0.35,"46":0.35}'::jsonb, 0.7, 12),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 13)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (15, 'Frühjahrspflege X13 (KW 15)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":2},{"titel":"Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":2},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2},{"titel":"Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen","stunden":2},{"titel":"Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand","stunden":0.35}]'::jsonb, 15.35),
  (23, 'Sommerpflege X13 (KW 23)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":2},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2}]'::jsonb, 9),
  (31, 'Sommerpflege X13 (KW 31)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":2},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2}]'::jsonb, 9),
  (38, 'Sommerpflege X13 (KW 38)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":2},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2}]'::jsonb, 9),
  (46, 'Herbstpflege X13 (KW 46)', '[{"titel":"Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochb","stunden":2},{"titel":"Rückschnitt / Trimmen Gehölze","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen) & All","stunden":2},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":3},{"titel":"Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von P","stunden":2},{"titel":"Abbau von Schläuchen und wasserführenden Teilen und Erinneru","stunden":0.5},{"titel":"Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterb","stunden":2},{"titel":"Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand","stunden":0.35}]'::jsonb, 13.85)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── Seebadstr · Seebadstr. 37, 13467 Berlin · 26 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('allcura-pflege', 'Seebadstr. 37', 2026, 'aktiv', '')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":1},{"von_monat":10,"bis_monat":10,"turnus":"einmalig","stunden_pro_gang":2}]'::jsonb, '{"30":1,"38":1,"43":2}'::jsonb, 4, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'pflanzen', '[{"von_monat":10,"bis_monat":12,"turnus":"monatlich","stunden_pro_gang":4}]'::jsonb, '{"43":4,"48":4,"52":4}'::jsonb, 12, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[{"von_monat":6,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":2}]'::jsonb, '{"26":2,"30":2,"34":2,"38":2,"43":2}'::jsonb, 10, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen. Kontrolle von Bewässerungssystemen.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC).', 'Auffüllen von Bewässerungseinheiten (IBC).', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 8),
    ('dachgarten', 'Dachgarten: Pflege des Dachgartens mit Rückschnitt von Ge…', 'Dachgarten: Pflege des Dachgartens mit Rückschnitt von Gehölzen, Mulchen, Pflanzenschutz, Düngen, Bodenverbesserung, Entfernung von Beikräutern, Kontrolle und Wartung der Bewässerungsanlage inkl. Frostsicherung und Inbetriebnahme, Nachpflanzungen sowie laufende Pflege von Stauden, Gräsern und Dachabläufen. Kommunikation mit Stakeholdern.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zust…', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand und Kompostreifung', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 12),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 13)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (26, 'Sommerpflege Seebadstr (KW 26)', '[{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2}]'::jsonb, 2),
  (30, 'Sommerpflege Seebadstr (KW 30)', '[{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2}]'::jsonb, 3),
  (34, 'Sommerpflege Seebadstr (KW 34)', '[{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2}]'::jsonb, 2),
  (38, 'Sommerpflege Seebadstr (KW 38)', '[{"titel":"Rückschnitt / Trimmen Gehölze","stunden":1},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2}]'::jsonb, 3),
  (43, 'Herbstpflege Seebadstr (KW 43)', '[{"titel":"Rückschnitt / Trimmen Gehölze","stunden":2},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":4},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":2}]'::jsonb, 8),
  (48, 'Herbstpflege Seebadstr (KW 48)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":4}]'::jsonb, 4),
  (52, 'Winter Seebadstr (KW 52)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":4}]'::jsonb, 4)
) as g(kw, titel, aufgaben, soll_stunden);

-- ── Roedernstr · Roedernstr. 17/19. 13467 Berlin · 52 h ─────────────────────────
with p as (
  insert into pflege_plaene (project_id, objekt, jahr, status, notizen)
  values ('allcura-pflege', 'Roedernstr. 17/19', 2026, 'aktiv', '')
  returning id
), a as (
  insert into pflege_aufgaben (plan_id, katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  select p.id, x.* from p cross join (values
    ('stauden_beikraut', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Ho…', 'Entfernung alter Pflanzenteile (Stauden),Beikräutern + Hochbinden von Kletterpflanzen', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 0),
    ('gehoelzschnitt', 'Rückschnitt / Trimmen Gehölze', 'Rückschnitt / Trimmen Gehölze', 'pflanzen', '[{"von_monat":7,"bis_monat":7,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":9,"bis_monat":9,"turnus":"einmalig","stunden_pro_gang":2},{"von_monat":10,"bis_monat":10,"turnus":"einmalig","stunden_pro_gang":4}]'::jsonb, '{"30":2,"38":2,"43":4}'::jsonb, 8, 1),
    ('duengen', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'Düngen (Hornspäne, Brennesseljauche, Grasschnitt etc.)', 'pflanzen', '[]'::jsonb, '{}'::jsonb, 0, 2),
    ('wege_reinigung', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'Reinigung der Wegeflächen (Laub, Beikräuter entfernen)', 'pflanzen', '[{"von_monat":10,"bis_monat":12,"turnus":"monatlich","stunden_pro_gang":8}]'::jsonb, '{"43":8,"48":8,"52":8}'::jsonb, 24, 3),
    ('mahd', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten dur…', 'Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch Rückschnitt. Sitzflächen freihalten.', 'pflanzen', '[{"von_monat":6,"bis_monat":10,"turnus":"monatlich","stunden_pro_gang":4}]'::jsonb, '{"26":4,"30":4,"34":4,"38":4,"43":4}'::jsonb, 20, 4),
    ('bewaesserung', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern vo…', 'Bewässerung (Per Hand/Flächenregner) Manuelles Wässern von Pflanzflächen und Gehölzen. Regelmäßige Anwuchs- oder Pflegewässerung der Kulturen. Kontrolle von Bewässerungssystemen.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 5),
    ('bew_winterfest', 'Abbau von Schläuchen und wasserführenden Teilen und Erinn…', 'Abbau von Schläuchen und wasserführenden Teilen und Erinnerung an AG abstellen von Außen-Wasseranschlüssen (Winterfest machen) IBC entleeren', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 6),
    ('bew_anschluss', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müs…', 'Anschließen/Kontrolle Bewässerungssystem. Im Frühjahr müssen Bewässerungssysteme angeschlossen und aktiviert werden. Wasserhähne müssen in Absprache mit AG eingschaltet werden.', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 7),
    ('ibc_auffuellen', 'Auffüllen von Bewässerungseinheiten (IBC).', 'Auffüllen von Bewässerungseinheiten (IBC).', 'bewaesserung', '[]'::jsonb, '{}'::jsonb, 0, 8),
    ('dachgarten', 'Dachgarten: Pflege des Dachgartens mit Rückschnitt von Ge…', 'Dachgarten: Pflege des Dachgartens mit Rückschnitt von Gehölzen, Mulchen, Pflanzenschutz, Düngen, Bodenverbesserung, Entfernung von Beikräutern, Kontrolle und Wartung der Bewässerungsanlage inkl. Frostsicherung und Inbetriebnahme, Nachpflanzungen sowie laufende Pflege von Stauden, Gräsern und Dachabläufen. Kommunikation mit Stakeholdern.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 9),
    ('nachpflanzung', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Abst…', 'Neupflanzungen/Nachpflanzungen. Bei Pflanzenausfall, Absterben, o.ä. ist die Nachpflanzung manchmal notwendig. Die Arten müssen abgestimmt werden.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 10),
    ('mulchen', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem si…', 'Nach-Mulchen (Bereits gemulchte Flächen müssen nachdem sich die Mulchschicht zersetzt wieder nachgemulcht werden)', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 11),
    ('bioreaktor', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zust…', 'Überprüfung von Bioreaktoren/Fermenter auf Funktion, Zustand und Kompostreifung', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 12),
    ('extra_waesserung', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Nieder…', 'Extra-Wässerung bei Hitzeperioden. Beobachtung der Niederschläge - ggf. Extra Bewässerung einplanen wenn notwendig zum Erhalt der Kulturen.', 'spezial', '[]'::jsonb, '{}'::jsonb, 0, 13)
  ) as x(katalog_key, titel, beschreibung, kategorie, fenster, wochen, jahres_stunden, sort_order)
  returning 1
)
insert into pflege_gaenge (plan_id, jahr, kw, titel, aufgaben, soll_stunden)
select p.id, 2026, g.* from p cross join (values
  (26, 'Sommerpflege Roedernstr (KW 26)', '[{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4}]'::jsonb, 4),
  (30, 'Sommerpflege Roedernstr (KW 30)', '[{"titel":"Rückschnitt / Trimmen Gehölze","stunden":2},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4}]'::jsonb, 6),
  (34, 'Sommerpflege Roedernstr (KW 34)', '[{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4}]'::jsonb, 4),
  (38, 'Sommerpflege Roedernstr (KW 38)', '[{"titel":"Rückschnitt / Trimmen Gehölze","stunden":2},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4}]'::jsonb, 6),
  (43, 'Herbstpflege Roedernstr (KW 43)', '[{"titel":"Rückschnitt / Trimmen Gehölze","stunden":4},{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":8},{"titel":"Mahd & Trimmen der Rasenflächen. Wegeflächen erhalten durch ","stunden":4}]'::jsonb, 16),
  (48, 'Herbstpflege Roedernstr (KW 48)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":8}]'::jsonb, 8),
  (52, 'Winter Roedernstr (KW 52)', '[{"titel":"Reinigung der Wegeflächen (Laub, Beikräuter entfernen)","stunden":8}]'::jsonb, 8)
) as g(kw, titel, aufgaben, soll_stunden);
